# fly.toml app configuration file generated for kjon-life on 2024-03-10T16:49:53-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'v2-kjon-life'
primary_region = 'iad'
kill_signal = "SIGTERM"
kill_timeout = 30
swap_size_mb = 512


[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
